services:

    react:
        build:
            context: ./frontend
            dockerfile: Dockerfiledev
        container_name: frontend
        volumes:
            - ./frontend:/usr/src/frontend
        ports:
            - "3000:3000"
        depends_on:
            - django

    django:
        build:
            context: ./app
            dockerfile: Dockerfile
        container_name: django
        command: >
            sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
        volumes:
            - ./app:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb

    pgdb:
        image: postgres:latest
        container_name: pgdb
        environment:
        - POSTGRES_DB=credit_offer_app
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        volumes:
            - pgdata:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 5050
        ports:
            - "15080:5050"
        volumes:
            - pgadmin-data:/var/lib/pgadmin/
        depends_on:
            -   pgdb

volumes:
    pgdata:
    pgadmin-data: