services:

    # react:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile
    #     container_name: frontend
    #     volumes: # Necessary for development purposes
    #         - ./frontend:/usr/src/frontend:delegated
    #         - /usr/src/frontend/node_modules
    #     environment: # Necessary for development purposes
    #         - CHOKIDAR_USEPOLLING=true
    #         - WATCHPACK_POLLING=true
    #     ports:
    #         - "3000:80"
    #     depends_on:
    #         - django

    django:
        build:
            context: ./app
            dockerfile: Dockerfile
        container_name: django
        models:
            llm:
                endpoint_var: LLM_URL
                model_var: LLM_NAME
        command: >
            sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py seed_db &&
            python manage.py runserver 0.0.0.0:8000
            "
        secrets:
            - gemini_api_key
            - gmail_user_email
            - gmail_app_password
        environment:
            - RISK_THRESHOLD=0.25
            - DEFAULT_EMAIL_RECEIVER=solo_tan@abv.bg
        volumes:
            - ./app:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb

    client_management: 
        build: 
            context: ./services/client_management
            dockerfile: Dockerfile
        container_name: client_management
        restart: "no"
        environment:
            - RISK_THRESHOLD=0.25
        volumes:
            - ./ml/output:/usr/src/services/client_management/ml/output
        depends_on:
            - django

    feedback_management: 
        build: 
            context: ./services/feedback_management
            dockerfile: Dockerfile
        container_name: feedback_management
        restart: "no"
        secrets:
            - gemini_api_key
        depends_on:
            - django
    
    pgdb:
        image: postgres:latest
        container_name: pgdb
        environment:
        - POSTGRES_DB=credit_offer_app
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        volumes:
            - pgdata:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 5050
        ports:
            - "15080:5050"
        volumes:
            - pgadmin-data:/var/lib/pgadmin/
        depends_on:
            -   pgdb

models:
    llm:
        model: ai/gemma3
        context_size: 4096
        runtime_flags:
        - "--verbose"                       # Set verbosity level to infinity
        - "--verbose-prompt"                # Print a verbose prompt before generation
        - "--log-prefix"                    # Enable prefix in log messages
        - "--log-timestamps"                # Enable timestamps in log messages
        - "--log-colors" 
        
volumes:
    pgdata:
    pgadmin-data:

secrets:
    gemini_api_key:
        file: secrets/gemini_api_key.txt

    gmail_user_email:
        file: secrets/gmail_user_email.txt

    gmail_app_password:
        file: secrets/gmail_app_password.txt