from django.db import models

class AgentFeedback(models.Model):
    """Model to store agent feedback summary, generated by LLM based on actual moderator Feedback.

    Attributes:
        - id: Primary key of the model.
        - feedback: Feedback generated by LLM based on actual moderator comments.
        - is_reviewed: Boolean indicating whether feedback has been reviewed.
        - created_at: Date and time the feedback was generated.
    """

    id = models.AutoField(primary_key=True)
    feedback = models.TextField(null=False)
    is_reviewed = models.BooleanField(null=False, default=False)
    created_at = models.DateTimeField(auto_now_add=True)