# Generated by Django 5.2.4 on 2025-08-23 15:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.FloatField(help_text='Interest rate as a decimal (e.g. 0.05 = 5%)')),
                ('amount_start', models.FloatField(help_text='Minimum loan amount')),
                ('amount_end', models.FloatField(help_text='Maximum loan amount')),
                ('duration', models.IntegerField(help_text='Duration of loan in months')),
                ('description', models.CharField(help_text='Short description of the loan', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_moderator', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_number', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('job', models.IntegerField(choices=[(0, 'Jobless'), (1, 'Low_Skill'), (2, 'Medium_Skill'), (3, 'High_Skill')])),
                ('housing', models.CharField(choices=[('own', 'Own'), ('rent', 'Rent'), ('free', 'Free')], max_length=5)),
                ('saving_account', models.CharField(choices=[('NA', 'Na'), ('little', 'Little'), ('moderate', 'Moderate'), ('rich', 'Rich'), ('quite rich', 'Quite Rich')], max_length=20)),
                ('checking_account', models.CharField(choices=[('NA', 'Na'), ('little', 'Little'), ('moderate', 'Moderate'), ('rich', 'Rich')], max_length=20)),
                ('credit_amount', models.IntegerField()),
                ('duration', models.IntegerField(default=12)),
                ('purpose', models.CharField(choices=[('car', 'Car'), ('furniture/equipment', 'Furniture Or Equipment'), ('radio/TV', 'Radio Or Tv'), ('domestic appliances', 'Domestic Appliances'), ('repairs', 'Repairs'), ('education', 'Education'), ('business', 'Business'), ('vacation/others', 'Vacation Or Others')], max_length=100)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email_content', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator_feedback', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('loan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_ended', models.DateTimeField(auto_now=True)),
                ('message_history', models.TextField(default='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credit_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.creditoffer')),
            ],
        ),
    ]
