# Generated by Django 5.2.4 on 2025-08-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoffer',
            name='unique_id',
        ),
    ]
