# Generated by Django 5.2.4 on 2025-08-05 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoffer',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='email_content',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='loan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.loan'),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='moderator_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
