# Generated by Django 5.2.4 on 2025-08-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoffer',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loan'),
        ),
    ]
