# Generated by Django 5.2.4 on 2025-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_creditoffer_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoffer',
            name='email_content',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
