# Generated by Django 5.2.4 on 2025-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_creditoffer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
