# Generated by Django 5.2.4 on 2025-08-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creditoffer_is_draft_alter_creditoffer_email_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoffer',
            name='expires_at',
        ),
    ]
