# Generated by Django 5.2.4 on 2025-08-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoffer',
            name='email_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
