# Generated by Django 5.2.4 on 2025-08-09 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_creditoffer_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='time_started',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat',
            name='credit_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.creditoffer'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
