# Generated by Django 5.2.4 on 2025-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creditoffer_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identity_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
