# Generated by Django 5.2.4 on 2025-08-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chat_time_started_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_history',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
