# Generated by Django 5.2.4 on 2025-08-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoffer',
            name='is_accepted',
            field=models.BooleanField(),
        ),
    ]
