# Generated by Django 5.2.4 on 2025-08-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_task_description', models.TextField(null=True)),
                ('default_task_description', models.TextField(default="Draft a professional and compliant credit approval email using the provided client, offer,\n    and company context. The email must clearly present the approved offer details, next steps,\n    and any required documents, while maintaining a courteous, trustworthy tone appropriate\n    for a regulated financial institution. At the end the recepient should be prompted to view the offer details via {more_details_link}. \n    The client name is {client_name}. The client is requesting the loan of {loan_amount} in euros, that he pledges to pay for approximately {loan_duration} in months.\n    When describing the loan, adhere to the generic loan description, provided by the credit bank - {loan_type_description}. \n    Also please keep in mind the demographic details of the person sucha as age - {client_age}, sex - {client_sex}.\n    Do not explicitly mention them, just adjust your tone based on the client's demographic situation, so that the email sounds more appealing to the client.\n    As next steps, make sure to prompt the user to accept the offer, if they like it, and book a consulting hour with a specialist at {bank_address} through {bank_phone_number}.\n    Make sure to end the email with a formal regard from SmartCredit. You can use emojis if the demographic situation of the customer finds it suitable.")),
            ],
        ),
    ]
