# Generated by Django 5.2.4 on 2025-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='checking_account',
            field=models.CharField(choices=[('unknown', 'Na'), ('little', 'Little'), ('moderate', 'Moderate'), ('rich', 'Rich')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='saving_account',
            field=models.CharField(choices=[('unknown', 'Na'), ('little', 'Little'), ('moderate', 'Moderate'), ('rich', 'Rich'), ('quite rich', 'Quite Rich')], max_length=20),
        ),
    ]
