# Generated by Django 5.2.4 on 2025-08-28 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_checking_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='checking_account',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('little', 'Little'), ('moderate', 'Moderate'), ('rich', 'Rich')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='saving_account',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('little', 'Little'), ('moderate', 'Moderate'), ('rich', 'Rich'), ('quite rich', 'Quite Rich')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='moderator_feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
